[cosmic-ray]
module-path = ["src/acquisition"]
timeout = 5.0
excluded-modules = []
test-command = "python -m pytest --size=50 --generator=random -c tests/pytest_random.toml src/tests/randtest.py"

[cosmic-ray.distributor]
name = "local"
