BEGIN TRANSACTION;
CREATE TABLE "ProjectSchemaVersion"("Version" INTEGER, "Comment" TEXT);
INSERT INTO ProjectSchemaVersion VALUES(4,'Towed');
CREATE TABLE Stations (  ID INTEGER PRIMARY KEY AUTOINCREMENT,  TaskID INTEGER,    SpreadPositionID INTEGER,   PosX REAL DEFAULT 0,     PosY REAL DEFAULT 0,     PosZ REAL DEFAULT 0,     "Time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE Tasks (  ID INTEGER PRIMARY KEY AUTOINCREMENT,  "Name" TEXT,      "Active" INTEGER DEFAULT 0,    PosX REAL,       PosY REAL,  PosZ REAL,  SpacingX REAL DEFAULT 1.0,       SpacingY REAL DEFAULT 1.0,  SpacingZ REAL DEFAULT 1.0,  ArrayCode INTEGER DEFAULT -1,   "Time" timestamp DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE DP_ABMN (  ID INTEGER PRIMARY KEY AUTOINCREMENT,  TaskID INTEGER,    DPKEY TEXT,   APosX REAL DEFAULT 0,     APosY REAL DEFAULT 0,     APosZ REAL DEFAULT 0,     BPosX REAL DEFAULT 0,     BPosY REAL DEFAULT 0,     BPosZ REAL DEFAULT 0,     MPosX REAL DEFAULT 0,     MPosY REAL DEFAULT 0,     MPosZ REAL DEFAULT 0,     NPosX REAL DEFAULT 0,     NPosY REAL DEFAULT 0,     NPosZ REAL DEFAULT 0,     FocusX REAL,       FocusY REAL,       FocusZ REAL,       "Ready" INTEGER DEFAULT 0,   Note TEXT DEFAULT NULL,   Mode integer default 0,   ModeValue real default NULL,  CONSTRAINT "DATAPOINT_UNIQUE_" UNIQUE    (TaskID, DPKEY));
CREATE INDEX DP_ABMN_TASKFOCUS on DP_ABMN (TaskID, FocusX, FocusY);
CREATE TABLE "Sessions"(  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,  "Time" timestamp DEFAULT CURRENT_TIMESTAMP,  "TaskID" INTEGER,   "InstrumentSerial" TEXT,   "InstrumentSoftware" TEXT,   "TransmitterSerial" TEXT,   "TransmitterSoftware" TEXT );
CREATE TABLE "Measures"(  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,  StationID INTEGER,       "PosLatitude" REAL,        "PosLongitude" REAL,       "PosQuality" INTEGER,    "Time" timestamp DEFAULT CURRENT_TIMESTAMP,    "IntPowerVolt" REAL DEFAULT 0,   "ExtPowerVolt" REAL DEFAULT 0,   "Temp" REAL DEFAULT 0,   "Light" REAL DEFAULT 0,  SessionID INTEGER default -1,   PositionId INTEGER default NULL    );
CREATE TABLE DP_MEASURE (  ID INTEGER PRIMARY KEY AUTOINCREMENT,  DPID INTEGER,        MeasureID INTEGER,   "Ready" INTEGER DEFAULT 0,   CONSTRAINT "DP_MEASURE_UNIQUE_" UNIQUE    (DPID,MeasureID));
CREATE INDEX DPV_MEASURE_DPID on DP_MEASURE (DPID);
CREATE INDEX DPV_MEASURE_MEASUREID on DP_MEASURE(MeasureID);
CREATE TABLE "Datatype"("ID" INTEGER PRIMARY KEY,"Name" TEXT,"Unit" TEXT, "Explanation" TEXT);
INSERT INTO Datatype VALUES(1,'SP','V','SP');
INSERT INTO Datatype VALUES(2,'ρapp','Ωm','Apparent Resistivity value');
INSERT INTO Datatype VALUES(3,'IP','mV/V','One IP window. Can be recalculated');
INSERT INTO Datatype VALUES(4,'SNR','dB','Signal to noice ratio');
INSERT INTO Datatype VALUES(5,'R','Ω','Resistance');
INSERT INTO Datatype VALUES(6,'I','A','Current');
INSERT INTO Datatype VALUES(7,'ΔU','V','ResDeltaVoltage');
INSERT INTO Datatype VALUES(8,'t','ms','Chargeability');
INSERT INTO Datatype VALUES(9,'IPΔU','V','IPDeltaVoltage');
INSERT INTO Datatype VALUES(10,'Avg','V','Average');
INSERT INTO Datatype VALUES(11,'Signal','V','Intermediary result');
INSERT INTO Datatype VALUES(12,'IPSP','V','Sp compensation');
INSERT INTO Datatype VALUES(13,'Temp','C','Temperature');
INSERT INTO Datatype VALUES(14,'P','W','Power');
INSERT INTO Datatype VALUES(15,'l','m','Length');
INSERT INTO Datatype VALUES(16,'MinMax','%','(Max-Min)/Min');
CREATE TABLE DPV (  ID INTEGER PRIMARY KEY AUTOINCREMENT,  TaskID INTEGER,      MeasureID INTEGER,   DPID INTEGER,        Channel INTEGER,     SeqNum INTEGER,      DatatypeID INTEGER,  DataValue REAL,      DataSDev REAL,       ADValue INTEGER,     ADRange INTEGER,     "Status" INTEGER DEFAULT 0,   N INTEGER,            MCycles INTEGER DEFAULT 1,       DataSDevType INTEGER DEFAULT 0);
CREATE INDEX DPV_DPID on DPV (DPID);
CREATE TABLE "EventSources"("ID" INTEGER PRIMARY KEY, "Name" TEXT);
INSERT INTO EventSources VALUES(1,'Instrument');
INSERT INTO EventSources VALUES(2,'RemoteControl');
INSERT INTO EventSources VALUES(3,'Console');
INSERT INTO EventSources VALUES(4,'User');
INSERT INTO EventSources VALUES(5,'Error');
INSERT INTO EventSources VALUES(6,'Power source');
INSERT INTO EventSources VALUES(7,'SAS Remote Control Protocol');
INSERT INTO EventSources VALUES(8,'Switch');
INSERT INTO EventSources VALUES(9,'Receiver');
INSERT INTO EventSources VALUES(10,'Transmitter');
INSERT INTO EventSources VALUES(11,'GPS');
INSERT INTO EventSources VALUES(12,'WLAN');
INSERT INTO EventSources VALUES(13,'3G');
CREATE TABLE "Log"(       "ID" INTEGER PRIMARY KEY AUTOINCREMENT,       "Time" timestamp DEFAULT CURRENT_TIMESTAMP,       "PosLatitude" REAL,       "PosLongitude" REAL,       "PosQuality" INTEGER,        "IntPowerVolt" REAL,        "ExtPowerVolt" REAL,        "Temp" REAL,        "Light" REAL,        "SourceTypeID" INTEGER,        "SourceID" TEXT,       "TaskID" INTEGER,       "MeasureID" INTEGER,       "WhatEnglish" TEXT,       "What" TEXT,        "Data" BLOB,       "EventClass"  int default 0,            "EventClassId"  TEXT default '');
CREATE TABLE ElectrodeTestData (  ID INTEGER PRIMARY KEY AUTOINCREMENT,  TaskID INTEGER,    StationID INTEGER,   SwitchNumber INTEGER,    SwitchAddress INTEGER,   PosX REAL DEFAULT 0,     PosY REAL DEFAULT 0,     PosZ REAL DEFAULT 0,     ResistanceValue REAL,    CurrentValue Real,       TestStatus INTEGER,      UserSetting INTEGER,     TxStatus INTEGER,        "Time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,   PositionId integer default NULL );
CREATE TABLE ExternalData (  ID INTEGER PRIMARY KEY AUTOINCREMENT,  TaskID INTEGER,      InstrID TEXT,        MeasureID INTEGER,   PhaseID INTEGER,     PhaseType INTEGER,   PhasePolarity INTEGER,   DatatypeID INTEGER,  DataValue REAL,      DataSDev REAL,       "Status" INTEGER DEFAULT 0,   N INTEGER          );
CREATE TABLE DatasetItems (  Id          integer PRIMARY KEY AUTOINCREMENT,  DataSetsId  integer,  MeasureID   integer,  DPID        integer);
CREATE TABLE Datasets (  Id          integer PRIMARY KEY AUTOINCREMENT,  Name        text,  ExcludeSet  boolean DEFAULT 1);
CREATE TABLE Positions (  Id          integer PRIMARY KEY AUTOINCREMENT,  TaskId integer DEFAULT -1,   PositionType        integer,   PosX REAL DEFAULT 0,     PosY REAL DEFAULT 0,     PosZ REAL DEFAULT 0,     IsRemote integer default 0,   MeasureID   integer DEFAULT -1,   MeasurePhase integer DEFAULT 0,   MeasureTime REAL DEFAULT 0  );
CREATE INDEX PositionsIndex on Positions (MeasureID);
CREATE TABLE GPSPositions (  Id          integer PRIMARY KEY AUTOINCREMENT,  PositionID   integer DEFAULT -1,   GPSSOURCE integer DEFAULT 0,   smask integer DEFAULT 0,   utc  timestamp DEFAULT CURRENT_TIMESTAMP,  sig integer default 0,  fix integer default 0,  PDOP REAL  DEFAULT 0,   HDOP REAL DEFAULT 0,    VDOP REAL DEFAULT 0,    LAT REAL DEFAULT 0,     LON REAL DEFAULT 0,  ELV REAL DEFAULT 0,     SPEED REAL DEFAULT 0,   DIRECTION REAL DEFAULT 0,  INUSE integer DEFAULT 0,   INVIEW integer DEFAULT 0,   satinfo TEXT DEFAULT NULL   );
CREATE INDEX GPSPositionsIndex on GPSPositions (PositionID);
CREATE TABLE CommonSchemaVersion (Version INTEGER, Comment TEXT);
INSERT INTO CommonSchemaVersion VALUES(3,'Utveckling');
CREATE TABLE Electrodes (  ID INTEGER PRIMARY KEY AUTOINCREMENT,  SpreadID INTEGER,    PosX INTEGER,     PosY INTEGER,     PosZ INTEGER,     CurrentElectrode INTEGER,     PotentialElectrode INTEGER,   RemoteElectrode INTEGER,      SwitchNumber INTEGER,    SwitchAddress INTEGER,   Cable INTEGER,    Takeout TEXT    );
CREATE TABLE TaskSettings ( key1 INTEGER NOT NULL, key2 INTEGER NOT NULL, Setting TEXT NOT NULL, Value TEXT, Auto INTEGER DEFAULT 0, CONSTRAINT TaskSettings_primary_key PRIMARY KEY (key1,key2,Setting) );
CREATE TABLE AcqSettings ( key1 INTEGER NOT NULL, key2 INTEGER NOT NULL, Setting TEXT NOT NULL, Value TEXT, Auto INTEGER DEFAULT 0, CONSTRAINT AcqSettings_primary_key PRIMARY KEY (key1,key2,Setting) );
COMMIT;
