[cosmic-ray]
module-path = ["acquisition"]
timeout = 120
excluded-modules = ["tests"]
test-command = "python -m pytest --size=100 -c tests/pytest_random.toml"

[cosmic-ray.distributor]
name = "local"
